### PR TITLE
Create test.md

### PR DESCRIPTION
**Pull request by marshallbao**
## Summary by CodeRabbit

- **Documentation**
	- Updated instructions for Python package management, including offline installation and version checking.
	- Added detailed guide on using virtual environment tools like `venv`, `virtualenv`, and `pipenv`.

### CODE REVIEW

**Comment by bianjieops** [comment]
@coderabbitai  可以给我提供下关于 md 写作的建议吗？

**Comment by marshallbao** [comment]
@coderabbitai 可以给我提供下关于 md 写作的建议吗？

**Comment by bianjieops** [comment]
> Review Status

你好

**Comment by bianjieops** [comment]
> # Walkthrough
> The recent changes provide a comprehensive guide on Python package management and virtual environment tools. It covers how to check package versions, install packages offline, and use tools like `pip`, `venv`, `virtualenv`, and `pipenv`. The diff also includes practical examples and references for further learning.
> 
> # Changes
> File	Change Summary
> `test.md`	Added instructions on Python package management and virtual environment tools. Covered usage of `pip`, `venv`, `virtualenv`, and `pipenv`. Included examples and references for further reading.
> # Poem
> > 🐇 Hopping through the code, with changes in our stride,
> > In the season of the fall, where the leaves reside.
> > 🍂 Python packages we manage, with tools far and wide,
> > In virtual environments, our dependencies abide.
> > On this day in history, the first artificial satellite did glide,
> > 🛰️ Just like our updates, reaching new heights in their ride.
> > So let's celebrate these changes, with a sense of pride,
> > For in the world of code, we are the trusted guide. 🌐
> 
> Tips
> ### Chat with CodeRabbit Bot (`@coderabbitai`)
> * If you reply to a _review comment_  from CodeRabbit, the bot will automatically respond.
> * To engage with CodeRabbit bot directly around the specific lines of code in the PR, mention @coderabbitai in your review comment
> * Note: Review comments are made on code diffs or files, not on the PR overview.
> * Add `@coderabbitai ignore` anywhere in the PR description to prevent this PR from being reviewed.
> 
> ### CodeRabbit Commands (invoked as PR comments)
> * `@coderabbitai pause` to pause the reviews on a PR.
> * `@coderabbitai resume` to resume the paused reviews.
> * `@coderabbitai review` to trigger a review. This is useful when automatic reviews are disabled for the repository.
> * `@coderabbitai help` to get help.
> * `@coderabbitai resolve` to resolve all the CodeRabbit review comments.
> 
> Note: For conversation with the bot, please use the review comments on code diffs or files.
> 
> ### CodeRabbit Configration File (`.coderabbit.yaml`)
> * You can programmatically configure CodeRabbit by adding a `.coderabbit.yaml` file to the root of your repository.
> * The JSON schema for the configuration file is available [here](https://coderabbit.ai/integrations/coderabbit-overrides.v2.json).
> * If your editor has YAML language server enabled, you can add the path at the top of this file to enable auto-completion and validation: `# yaml-language-server: $schema=https://coderabbit.ai/integrations/coderabbit-overrides.v2.json`

@coderabbitai 你好

**Pull request merged**
